name: Playwright E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [chromium, firefox, webkit, 'iPhone 14']  # Run all browsers + mobile emulation
      fail-fast: false  # Continue running other matrix jobs even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers & dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests for ${{ matrix.project }}
        run: npx playwright test --project="${{ matrix.project }}" --reporter=html

      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
